services:
  db:
    image: postgres:16
    container_name: sylvanian-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sylvanian
    ports:
      - "5432:5432"